"""Initial schema with SQLite support

Revision ID: 156ce40ea7a5
Revises:
Create Date: 2026-01-22 21:41:04.993595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from src.models.types import GUID


# revision identifiers, used by Alembic.
revision: str = '156ce40ea7a5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backtest_results',
    sa.Column('backtest_id', GUID(), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('evaluation_period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('evaluation_period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('regime_breakdown', sa.JSON(), nullable=True),
    sa.Column('error_analysis', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('backtest_id')
    )
    op.create_table('entities',
    sa.Column('entity_id', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('entity_name', sa.String(length=200), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('entity_id')
    )
    op.create_table('market_data',
    sa.Column('ticker', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('vwap', sa.Float(), nullable=True),
    sa.Column('volatility_1d', sa.Float(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('ticker', 'timestamp', name='pk_market_data')
    )
    op.create_index('idx_market_data_ticker_time', 'market_data', ['ticker', 'timestamp'], unique=False)
    op.create_table('market_regimes',
    sa.Column('regime_id', GUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('regime', sa.JSON(), nullable=False),
    sa.Column('regime_probabilities', sa.JSON(), nullable=True),
    sa.Column('regime_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('regime_id')
    )
    op.create_index('idx_regime_time', 'market_regimes', ['timestamp'], unique=False)
    op.create_table('raw_news',
    sa.Column('news_id', GUID(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('full_text', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('author', sa.String(length=200), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('news_id'),
    sa.UniqueConstraint('content_hash'),
    sa.UniqueConstraint('url')
    )
    op.create_index('idx_raw_news_hash', 'raw_news', ['content_hash'], unique=False)
    op.create_index('idx_raw_news_published', 'raw_news', ['published_at'], unique=False)
    op.create_index('idx_raw_news_source', 'raw_news', ['source', 'published_at'], unique=False)
    op.create_table('data_quality_scores',
    sa.Column('news_id', GUID(), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('duplicate_of', GUID(), nullable=True),
    sa.Column('validation_flags', sa.JSON(), nullable=False),
    sa.Column('quality_issues', sa.JSON(), nullable=True),
    sa.Column('source_reliability_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['duplicate_of'], ['raw_news.news_id'], ),
    sa.ForeignKeyConstraint(['news_id'], ['raw_news.news_id'], ),
    sa.PrimaryKeyConstraint('news_id')
    )
    op.create_table('entity_relationships',
    sa.Column('relationship_id', GUID(), nullable=False),
    sa.Column('entity_from', sa.String(length=50), nullable=False),
    sa.Column('entity_to', sa.String(length=50), nullable=False),
    sa.Column('relationship_type', sa.String(length=50), nullable=False),
    sa.Column('strength', sa.Float(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entity_from'], ['entities.entity_id'], ),
    sa.ForeignKeyConstraint(['entity_to'], ['entities.entity_id'], ),
    sa.PrimaryKeyConstraint('relationship_id')
    )
    op.create_table('impact_scores',
    sa.Column('score_id', GUID(), nullable=False),
    sa.Column('news_id', GUID(), nullable=False),
    sa.Column('entity_id', sa.String(length=50), nullable=False),
    sa.Column('impact_score', sa.Float(), nullable=False),
    sa.Column('impact_breakdown', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('time_horizon', sa.String(length=20), nullable=True),
    sa.Column('expected_volatility_impact', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.entity_id'], ),
    sa.ForeignKeyConstraint(['news_id'], ['raw_news.news_id'], ),
    sa.PrimaryKeyConstraint('score_id')
    )
    op.create_index('idx_impact_entity_time', 'impact_scores', ['entity_id', 'created_at'], unique=False)
    op.create_table('news_entity_mapping',
    sa.Column('mapping_id', GUID(), nullable=False),
    sa.Column('news_id', GUID(), nullable=False),
    sa.Column('entity_id', sa.String(length=50), nullable=False),
    sa.Column('exposure_type', sa.String(length=20), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('mention_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.entity_id'], ),
    sa.ForeignKeyConstraint(['news_id'], ['raw_news.news_id'], ),
    sa.PrimaryKeyConstraint('mapping_id')
    )
    op.create_index('idx_mapping_entity', 'news_entity_mapping', ['entity_id', 'created_at'], unique=False)
    op.create_index('idx_mapping_news', 'news_entity_mapping', ['news_id'], unique=False)
    op.create_table('predictions',
    sa.Column('prediction_id', GUID(), nullable=False),
    sa.Column('entity_id', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('horizon', sa.String(length=10), nullable=False),
    sa.Column('direction_probabilities', sa.JSON(), nullable=False),
    sa.Column('expected_return', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('calibrated_confidence', sa.Float(), nullable=True),
    sa.Column('model_contributions', sa.JSON(), nullable=True),
    sa.Column('key_drivers', sa.JSON(), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('related_news_ids', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.entity_id'], ),
    sa.PrimaryKeyConstraint('prediction_id')
    )
    op.create_index('idx_predictions_created', 'predictions', ['created_at'], unique=False)
    op.create_index('idx_predictions_entity_time', 'predictions', ['entity_id', 'timestamp'], unique=False)
    op.create_table('processed_news',
    sa.Column('news_id', GUID(), nullable=False),
    sa.Column('summary_short', sa.Text(), nullable=True),
    sa.Column('summary_medium', sa.Text(), nullable=True),
    sa.Column('key_facts', sa.JSON(), nullable=True),
    sa.Column('sentiment', sa.JSON(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=True),
    sa.Column('event_subtype', sa.String(length=100), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('llm_metadata', sa.JSON(), nullable=True),
    sa.Column('processing_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['news_id'], ['raw_news.news_id'], ),
    sa.PrimaryKeyConstraint('news_id')
    )
    op.create_table('signal_decay_models',
    sa.Column('news_id', GUID(), nullable=False),
    sa.Column('initial_impact', sa.Float(), nullable=True),
    sa.Column('decay_rate', sa.Float(), nullable=True),
    sa.Column('half_life_days', sa.Float(), nullable=True),
    sa.Column('effective_window_days', sa.Integer(), nullable=True),
    sa.Column('model_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['news_id'], ['raw_news.news_id'], ),
    sa.PrimaryKeyConstraint('news_id')
    )
    op.create_table('surprise_scores',
    sa.Column('surprise_id', GUID(), nullable=False),
    sa.Column('news_id', GUID(), nullable=False),
    sa.Column('metric', sa.String(length=100), nullable=False),
    sa.Column('actual', sa.Float(), nullable=True),
    sa.Column('consensus', sa.Float(), nullable=True),
    sa.Column('surprise_raw', sa.Float(), nullable=True),
    sa.Column('surprise_normalized', sa.Float(), nullable=True),
    sa.Column('surprise_percentile', sa.Float(), nullable=True),
    sa.Column('market_priced_in', sa.Float(), nullable=True),
    sa.Column('true_surprise', sa.Float(), nullable=True),
    sa.Column('expected_reaction', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['news_id'], ['raw_news.news_id'], ),
    sa.PrimaryKeyConstraint('surprise_id')
    )
    op.create_table('prediction_outcomes',
    sa.Column('outcome_id', GUID(), nullable=False),
    sa.Column('prediction_id', GUID(), nullable=False),
    sa.Column('actual_return', sa.Float(), nullable=True),
    sa.Column('error', sa.Float(), nullable=True),
    sa.Column('direction_correct', sa.Boolean(), nullable=True),
    sa.Column('within_confidence_interval', sa.Boolean(), nullable=True),
    sa.Column('sharpe_contribution', sa.Float(), nullable=True),
    sa.Column('evaluation_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.prediction_id'], ),
    sa.PrimaryKeyConstraint('outcome_id')
    )
    op.create_index('idx_outcomes_prediction', 'prediction_outcomes', ['prediction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_outcomes_prediction', table_name='prediction_outcomes')
    op.drop_table('prediction_outcomes')
    op.drop_table('surprise_scores')
    op.drop_table('signal_decay_models')
    op.drop_table('processed_news')
    op.drop_index('idx_predictions_entity_time', table_name='predictions')
    op.drop_index('idx_predictions_created', table_name='predictions')
    op.drop_table('predictions')
    op.drop_index('idx_mapping_news', table_name='news_entity_mapping')
    op.drop_index('idx_mapping_entity', table_name='news_entity_mapping')
    op.drop_table('news_entity_mapping')
    op.drop_index('idx_impact_entity_time', table_name='impact_scores')
    op.drop_table('impact_scores')
    op.drop_table('entity_relationships')
    op.drop_table('data_quality_scores')
    op.drop_index('idx_raw_news_source', table_name='raw_news')
    op.drop_index('idx_raw_news_published', table_name='raw_news')
    op.drop_index('idx_raw_news_hash', table_name='raw_news')
    op.drop_table('raw_news')
    op.drop_index('idx_regime_time', table_name='market_regimes')
    op.drop_table('market_regimes')
    op.drop_index('idx_market_data_ticker_time', table_name='market_data')
    op.drop_table('market_data')
    op.drop_table('entities')
    op.drop_table('backtest_results')
    # ### end Alembic commands ###
